### PR TITLE
SPQR: allow user-selected ordering

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Here's a first draft. The design isn't very sophisticated.

I'm a bit confused when it comes to testing. When I run tests locally, I'm not sure if this module gets tested, or the one in stdlib.

**Comment by andreasnoack** [comment]
Oh. This would have to be against https://github.com/JuliaLang/julia/tree/master/stdlib/SuiteSparse. We created this repo when we thought we could migrate SuiteSparse out of Base before 1.0. It never happened.

**Comment by dpo** [comment]
OK, will do. There's something intriguing though:
```julia
julia> A = rand(10,6); b = rand(10);
julia> QR = qr(sparse(A), ordering=SuiteSparse.SPQR.ORDERING_FIXED);
julia> QR \ b
Float64[]
```
Any idea what's going on?

**Comment by dpo** [comment]
The issue is [this line](https://github.com/JuliaLinearAlgebra/SuiteSparse.jl/blob/master/src/spqr.jl#L390) because `F.cpiv` is empty when `ordering==ORDERING_FIXED`.

**Comment by dpo** [comment]
I fixed it by returning
```
return length(F.cpiv) == 0 ?  getindex(X, ntuple(i -> i == 1 ? (1:max(size(F,2), size(B,1))) : :, Val(ndims(B)))...) : getindex(X, ntuple(i -> i == 1 ? invperm(F.cpiv) : :, Val(ndims(B)))...)
```

**Comment by DilumAluthge** [comment]
Hi,

Thanks for the PR! Can you please open the PR against this repo instead: https://github.com/JuliaLang/SuiteSparse.jl

Thank you!

**Comment by dpo** [comment]
It’s already in there because I submitted this PR against base last year.

**Pull request closed without merging**
